### ISSUE TITLE
Music light example breaks on oneTimeExecution = false with hourly tasks

### ISSUE THREAD

**Issue by codeZeilen** [wbsg/ldif#5]
Hi :)

we've set the property oneTimeExecution in scheduler.properties to false and changed all ImportJobs and the IntegrationJob to an hourly schedule. We then get the following error:

```
Jun 3, 2014 5:21:18 PM de.fuberlin.wiwiss.silk.output.Output close
INFO: Wrote 269 links
Jun 3, 2014 5:21:18 PM de.fuberlin.wiwiss.silk.util.task.HasStatus$class updateStatus
INFO: Writing output finished in 2ms (100.0%)
[INFO] Time needed to link data: 0.304s
[INFO] Number of links generated by silk: 32
[INFO] Minting URIs...
[INFO] Start URI translation...
[INFO] End URI translation: Processed 10090 quads
[INFO] Time needed to translate URIs: 0.276s
[INFO] Writing integration output...
java.io.IOException: Stream closed
        at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:115)
        at java.io.BufferedWriter.write(BufferedWriter.java:220)
        at java.io.Writer.write(Writer.java:157)
        at ldif.output.SerializingQuadWriter.write(SerializingQuadWriter.scala:40)
        at ldif.local.IntegrationJob$$anonfun$writeOutput$1.apply(IntegrationJob.scala:670)
        at ldif.local.IntegrationJob$$anonfun$writeOutput$1.apply(IntegrationJob.scala:670)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at ldif.local.IntegrationJob.writeOutput(IntegrationJob.scala:670)
        at ldif.local.IntegrationJob.runIntegration(IntegrationJob.scala:191)
        at ldif.local.Scheduler.runIntegration(Scheduler.scala:122)
        at ldif.local.Scheduler$$anonfun$evaluateIntegrationJob$1.apply$mcV$sp(Scheduler.scala:88)
        at ldif.local.Scheduler$$anon$1.run(Scheduler.scala:308)
```

**Comment by codeZeilen** [comment]
Turns out this also happens when all integration subtasks are deactivated. Additionally the integration job is restarted right after it finished, although an hourly schedule is set. Right after this restart it crashes with the stack trace from above.

**Comment by amatteini** [comment]
Thanks!
